-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "instructorAddress" SET DEFAULT '',
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Instructor" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Learner" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
